extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_config(cbindgen::Config::from_file("./cbindgen.toml").unwrap())
        .with_crate(crate_dir)
        /*
           .with_language(cbindgen::Language::C)
        //.with_include_guard("__KERNEL_VM__")
        .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
        .with_include_version(true)
        .with_style(cbindgen::Style::Both)
        .with_documentation(true)
        .with_header("/* (c) 2022 KernelLabs. Licensed under Apache-2.0 */")
        */
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("bindings.h");
}
