[package]
name = "test1"
version = "0.0.0"

[dependencies]
MoveNursery = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib/nursery", rev = "70b34a66473c34ad30d101290b249f2db3c847a2" }

[addresses]
std = "0x1"
