[package]
name = "test1"
version = "0.0.0"

[dependencies]
MoveNursery = { local = "../stdlib/src/move_nursery" }
NovaStdlib = { local = "../stdlib/src/nova_stdlib" }


[addresses]
nova_std = "0x1"
std = "0x1"
TestAccount = "0x2"
