[package]
name = "NovaStdlib"
version = "1.5.0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "70b34a66473c34ad30d101290b249f2db3c847a2" }

[addresses]
std = "0x1"
nova_std = "0x1"
