extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
      .with_language(cbindgen::Language::C)
      .with_crate(crate_dir)
      .with_include_guard("__KERNEL_VM__")
      .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
      .with_include_version(true)
      .with_style(cbindgen::Style::Type)
      .generate()
      .expect("Unable to generate bindings")
      .write_to_file("bindings.h");
}
