#ifndef __KERNEL_VM__
#define __KERNEL_VM__

/* Generated with cbindgen:0.24.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Returns a version number of this library as a C string.
 *
 * The string is owned by libkernelvm and must not be mutated or destroyed by the caller.
 */
const char *version_str(void);

#endif /* __KERNEL_VM__ */
