name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - "release/*"
jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache move-cli
        id: cache-mv-cli
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/move
          key: ${{ '0.3.2' }}
      - name: Install move
        if: steps.cache-mv-cli.outputs.cache-hit != 'true'
        run: |
          cargo install mv-cli@0.3.2 --features address20
      - name: Build test contracts
        run: |
          (cd vm/move-test && move build)
      - name: Build rust
        run: |
          make build-rust
      - name: Run Test
        run: |
          make test
